name: Test

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  test-posix:
    name: Build and test on POSIX systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13 ]
    steps:
      - name: Checkout Janet
        uses: actions/checkout@v4
        with:
          repository: janet-lang/janet
          path: janet
          ref: refs/heads/master
      - name: Build Janet
        run: cd janet && make clean && make && make test
      - name: Install Janet
        run: cd janet && sudo make install
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: spork
      - name: Build Spork
        run: cd spork && janet -l ./bundle -e "(build)"
      - name: Test Install 
        run: sudo janet -e '(bundle/install "spork")'
      - name: Run Tests
        run: cd spork && janet -l ./bundle -e "(test)"

  test-windows:
    name: Build and test on Windows
    strategy:
      matrix:
        os: [ windows-latest, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: spork
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Download Janet Latest Release
        shell: cmd
        run: curl -fSLo janet.msi https://github.com/janet-lang/janet/releases/download/v1.36.0/janet-1.36.0-windows-x64-installer.msi
      - name: Install Janet
        shell: cmd
        run: msiexec /quiet /i janet.msi ALLUSERS=1 /log install.log && type install.log
      - name: Build Spork
        shell: cmd
        run: |
          cl.exe /? & refreshenv & cl.exe /? cd spork & "C:\Program Files\Janet\bin\janet.exe" -l ./bundle -e "(do (setdyn :verbose true) (build))"
      - name: Test Install 
        shell: cmd
        run: |
          refreshenv && "C:\Program Files\Janet\bin\janet.exe" -e "(bundle/install `spork`)"
      - name: Run Tests
        shell: cmd
        run: |
          refreshenv && cd spork && "C:\Program Files\Janet\bin\janet.exe" -l ./bundle -e "(test)"
